#pom文件中,以Maven为主，SpringBoot为辅.因为最后打包的是maven。
#多环境开发控制:Maven与SpringBoot多环境兼容（步骤），所以要保证兼容。


#设置启用的环境
#  SpringBoot中引用Maven属性
spring:
  profiles:
    active: dev


#yaml文件多环境启动
#yaml三个横杠分开不同环境
---
#开发
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 80


---
#生产
spring:
  config:
    activate:
      on-profile: pro
server:
  port: 81


---
#测试
spring:
  config:
    activate:
      on-profile: test

server:
  port: 82