spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatisplus_db?serverTimezone=UTC
    username: root
    password: 1234

  main:
    banner-mode: off  # 取消SpringBoot启动banner图标


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启mp的日志（输出到控制台）

# 全局策略配置，也就是所有的实体类都有的属性
  global-config:
    db-config:
      id-type: auto # id-type：设置主键属性的生成策略，值参照IdType枚举值
      table-prefix: tbl_  # table-prefix表名前缀
      logic-delete-field: deleted # 逻辑删除字段名
      logic-not-delete-value: 0 # 逻辑删除字面值：未删除为0
      logic-delete-value: 1 # 逻辑删除字面值：删除为1
#    banner: off  # 关闭mybatisplus启动图标



