spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatisplus_db?serverTimezone=UTC
    username: root
    password: 1234

  main:
    banner-mode: off  # 取消SpringBoot启动banner图标


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启mp的日志（输出到控制台）

  global-config:
    banner: off  # 关闭mybatisplus启动图标
