#设置启用的环境
spring:
  profiles:
    active: dev


#yaml文件多环境启动
#yaml三个横杠分开不同环境
---
#开发
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 80


---
#生产
spring:
  config:
    activate:
      on-profile: pro
server:
  port: 81


---
#测试
spring:
  config:
    activate:
      on-profile: test
server:
  port: 82

logging:
  level:
    com.wang: debug